@echo off
cd /d %~dp0
set GROQ_API_KEY=YOUR_GROQ_KEY
set TELEGRAM_BOT_TOKEN=YOUR_TELEGRAM_BOT_TOKEN
set TELEGRAM_CHAT_ID=YOUR_TELEGRAM_CHAT_ID
set CLUB_EMAIL=YOUR_CLUB_EMAIL
set CLUB_PASSWORD=YOUR_CLUB_PASSWORD
node bot.js
